import pandas as pd

DOCUMENTS = [
    {
        'id': 'doc_001',
        'title': 'Climate Change and Global Warming',
        'text': '''Climate change represents one of the most pressing environmental challenges of the 21st century. Rising global temperatures are fundamentally altering ecosystems and weather patterns worldwide. Scientific consensus confirms that human activities, particularly the burning of fossil fuels, are the primary driver of current warming trends. Since pre-industrial times, global average temperatures have risen approximately 1.1 degrees Celsius, with visible consequences already manifesting across the planet. Melting polar ice caps and glaciers contribute to rising sea levels that threaten coastal communities and island nations. Extreme weather events including devastating hurricanes, prolonged droughts, and unprecedented wildfires are becoming more frequent and intense. Ocean acidification from increased carbon dioxide absorption poses existential threats to marine ecosystems and fisheries that billions depend upon for food security. The agricultural sector faces mounting pressure as changing precipitation patterns and temperature extremes reduce crop yields in critical growing regions. Economic impacts are already significant, with climate-related disasters costing hundreds of billions annually in damages and recovery efforts. However, the transition to renewable energy and sustainable practices offers pathways to mitigate the worst outcomes while creating new economic opportunities.'''
    },
    {
        'id': 'doc_002',
        'title': 'Machine Learning in Healthcare',
        'text': '''Machine learning technologies are revolutionizing healthcare delivery and medical research across the globe. Diagnostic accuracy has improved dramatically in medical imaging, where deep learning algorithms now match or exceed the performance of experienced radiologists in detecting cancers and other abnormalities. Predictive models trained on vast patient datasets enable hospitals to identify high-risk individuals before complications develop, allowing for preventive interventions. Drug discovery pipelines have been accelerated by machine learning algorithms that screen millions of molecular compounds to identify promising candidates far faster than traditional laboratory methods. Clinical decision support systems powered by machine learning help physicians select optimal treatment plans based on comprehensive analysis of similar patient cases and outcomes. Natural language processing enables extraction of valuable insights from unstructured clinical notes, radiology reports, and patient records that were previously locked in text form. Personalized medicine becomes increasingly feasible as machine learning models consider individual genetic profiles, lifestyle factors, and medical history to recommend tailored treatments. However, successful implementation requires addressing concerns about data privacy, ensuring algorithmic transparency, and managing the inherent biases present in training data that may reflect historical healthcare disparities.'''
    },
    {
        'id': 'doc_003',
        'title': 'Supply Chain Disruptions 2023',
        'text': '''Global supply chains continue to experience significant disruptions stemming from geopolitical tensions, pandemic aftereffects, and climate-related events. Manufacturing facilities in critical regions face unexpected closures from floods, earthquakes, and extreme weather, cascading impacts through dependent industries. Semiconductor shortages persist as production cannot meet surging demand from electric vehicles, consumer electronics, and artificial intelligence applications. Port congestion and shipping container imbalances have created bottlenecks that extend delivery timelines and increase transportation costs substantially. Trade policy uncertainties and tariffs introduce unpredictability into procurement planning, forcing companies to develop alternative sourcing strategies. Labor shortages in logistics and warehousing sectors limit the ability to clear accumulated inventory efficiently. Companies are investing in supply chain resilience through supplier diversification, reshoring of critical components, and adoption of digital visibility technologies. Real-time tracking using IoT sensors and blockchain provides unprecedented transparency into product movement. Nearshoring initiatives bring production closer to consumption markets, reducing dependency on vulnerable long-distance routes. Strategic inventory buffering of critical materials and components helps mitigate future disruption risks.'''
    },
    {
        'id': 'doc_004',
        'title': 'Federal Reserve Interest Rate Policy',
        'text': '''The Federal Reserve's interest rate decisions profoundly influence economic activity, inflation dynamics, and financial market behavior. In response to elevated inflation reaching multi-decade highs, the Federal Reserve began raising interest rates in early 2022, marking the end of an extended period of accommodative monetary policy. The federal funds rate increased from near-zero levels to over four percent by mid-2023, representing the fastest rate hiking cycle in decades. Higher interest rates increase borrowing costs for consumers and businesses, cooling demand for loans and investments in expansion. Mortgage rates surged in tandem with fed rate increases, pricing many potential homebuyers out of the market and reducing housing demand. Commercial real estate markets faced increasing stress as higher financing costs reduced property valuations and refinancing became unviable for some borrowers. Equity markets experienced volatility as investors reassessed valuations in light of higher discount rates and reduced earnings expectations. The Federal Reserve faces a delicate balancing act between controlling inflation and avoiding excessive economic damage from overly restrictive policy. Achieving a soft landing where inflation moderates without triggering recession remains challenging. Ongoing policy decisions depend on economic data regarding inflation trends, employment strength, and financial system stability.'''
    },
    {
        'id': 'doc_005',
        'title': 'Electric Vehicle Market Growth',
        'text': '''The global electric vehicle market is experiencing explosive growth as technology improves, costs decline, and environmental regulations tighten. Battery costs have fallen by over eighty percent in the past decade, making electric vehicles increasingly price-competitive with gasoline-powered alternatives. Major automakers are pivoting toward electrification, announcing plans to phase out internal combustion engines entirely within fifteen to thirty years. Government incentives including purchase subsidies, tax credits, and infrastructure investments are accelerating adoption across developed nations. Charging infrastructure expansion is critical to adoption, with networks of fast chargers being deployed along highways and urban areas. Commercial vehicle electrification is advancing rapidly, with electric trucks and buses being deployed by logistics companies and public transit agencies. Battery technology continues evolving with higher energy density enabling longer driving ranges and faster charging times. Supply chain development for battery minerals including lithium, cobalt, and nickel is becoming strategically important as demand surges. Vehicle-to-grid technology allows electric vehicles to serve as mobile batteries, supporting grid stability and renewable energy integration. Used electric vehicle markets are developing as the first generation of electric vehicles reaches secondary markets, improving affordability.'''
    },
    {
        'id': 'doc_006',
        'title': 'Remote Work Productivity',
        'text': '''The shift to remote and hybrid work arrangements has fundamentally transformed workplace dynamics and organizational structures. Empirical studies demonstrate that remote workers often exhibit higher productivity than their office-based counterparts, with improved focus on deep work and fewer workplace distractions. Collaboration technology platforms including video conferencing, project management software, and instant messaging enable effective coordination despite geographic dispersion. Employee satisfaction often increases with remote work flexibility, allowing workers to balance professional responsibilities with family commitments and personal wellness. Companies report reduced real estate costs from downsizing office spaces as fewer employees require daily desk space. Recruitment and retention improve when organizations offer remote options, accessing talent pools beyond geographic boundaries and appealing to workers seeking flexibility. However, challenges emerge around maintaining company culture, onboarding new employees, and fostering spontaneous innovation that thrives through serendipitous in-person interactions. Mental health concerns including isolation, burnout, and difficulty maintaining work-life boundaries require intentional management and support programs. Hybrid models combining remote flexibility with periodic in-office collaboration emerge as optimal for many organizations. Successful remote work requires investment in technology infrastructure, clear communication protocols, and management practices emphasizing trust rather than surveillance.'''
    },
    {
        'id': 'doc_007',
        'title': 'Cybersecurity Threats 2024',
        'text': '''Cybersecurity threats continue evolving in sophistication and scope, posing existential risks to organizations across sectors. Ransomware attacks have become increasingly prevalent and damaging, with criminal organizations encrypting critical systems and demanding substantial payments for decryption keys. Supply chain attacks exploit vulnerabilities in software development and distribution, compromising downstream customers through compromised legitimate software. Nation-state actors conduct sophisticated espionage campaigns targeting government agencies, critical infrastructure, and defense contractors. Artificial intelligence capabilities are being weaponized to automate attack discovery and execution, creating tools that can adapt and evade traditional defenses. Data breaches expose sensitive personal and financial information, enabling identity theft and fraud affecting millions. Zero-day exploits targeting previously unknown vulnerabilities prove difficult to defend against without sophisticated threat intelligence. Cloud environment misconfigurations create unintended public access to sensitive data stored in cloud repositories. Internet of Things device proliferation expands the attack surface as billions of connected devices often lack adequate security hardening. Incident response capabilities and cyber insurance become essential components of organizational risk management. Regulatory frameworks imposing mandatory breach notification and accountability incentivize stronger security investments and practices.'''
    },
    {
        'id': 'doc_008',
        'title': 'Artificial Intelligence Market Trends',
        'text': '''Artificial intelligence markets are experiencing unprecedented growth as enterprises recognize transformative potential across business functions. Large language models like GPT variants demonstrate remarkable capabilities in natural language understanding and generation, enabling applications from customer service to content creation. Computer vision systems excel at image recognition and analysis tasks, powering autonomous vehicles, medical diagnostics, and manufacturing quality control. Reinforcement learning approaches enable systems to optimize complex decisions in robotics, resource allocation, and financial trading. Enterprise adoption accelerates as companies implement AI for customer personalization, fraud detection, supply chain optimization, and workforce analytics. Investment in AI startups and research continues surging, with venture capital and corporate funding reaching record levels. Ethical considerations including algorithmic bias, data privacy, and autonomous decision-making accountability create challenges for responsible deployment. Regulatory frameworks emerging globally, such as the European Union AI Act, establish requirements for transparency and impact assessment. Skilled AI practitioners command substantial compensation as competition for talent intensifies. Educational institutions expand AI and machine learning curriculum to address skill shortages in the developing workforce.'''
    },
    {
        'id': 'doc_009',
        'title': 'Renewable Energy Infrastructure',
        'text': '''Renewable energy sources including solar, wind, and hydroelectric power are rapidly displacing fossil fuels in global electricity generation. Solar photovoltaic installation costs have declined by eighty-nine percent since 2010, making solar increasingly cost-competitive with natural gas and coal in many regions. Wind energy capacity continues expanding, particularly offshore installations that generate power more consistently and with higher capacity factors than land-based systems. Battery storage technology has advanced significantly, addressing intermittency challenges that previously limited renewable penetration by enabling energy storage across diurnal cycles. Power grid modernization initiatives utilizing smart grid technologies enable better integration of distributed renewable resources and dynamic demand management. Vehicle-to-grid integration allows electric vehicle batteries to store excess renewable generation and discharge power back to the grid during peak demand. Green hydrogen produced through electrolysis using renewable electricity offers promise for decarbonizing industries including heavy manufacturing and transportation. Geothermal energy provides reliable baseload power in regions with suitable geology, complementing variable renewable sources. Investment in renewable energy infrastructure exceeded three hundred billion dollars annually, reflecting strong market confidence and policy support. However, continued expansion requires addressing supply chain dependencies on critical minerals and completion of grid infrastructure upgrades.'''
    },
    {
        'id': 'doc_010',
        'title': 'Quantum Computing Progress',
        'text': '''Quantum computing represents a paradigm shift in computational capability with profound implications for multiple scientific and industrial domains. Quantum processors harness superposition and entanglement to encode information in quantum bits, enabling simultaneous exploration of vast solution spaces. Current quantum systems operate with limited qubit counts, ranging from dozens to hundreds, introducing constraints on problem complexity that can be addressed. Quantum error correction remains an active research challenge, as quantum states are fragile and susceptible to decoherence from environmental interference. Near-term applications including drug discovery, molecular simulation, and optimization problems show promise where quantum advantage over classical computers is achievable. Cryptography faces both threats and opportunities as quantum computers could potentially break current encryption schemes, spurring development of quantum-resistant cryptography. Financial institutions explore quantum applications for portfolio optimization, risk analysis, and derivative pricing. Machine learning applications leveraging quantum processing show theoretical speedups for specific algorithm classes. Major technology companies including IBM, Google, and IonQ are advancing quantum hardware development and cloud-based quantum computing services. Decades likely remain before fully fault-tolerant quantum computers achieve widespread commercial deployment, requiring sustained investment in research and workforce development.'''
    }
]

def load_docs():
    return DOCUMENTS

def get_doc_text(doc_id):
    for doc in DOCUMENTS:
        if doc['id'] == doc_id:
            return doc['text']
    return None

def get_doc_by_id(doc_id):
    for doc in DOCUMENTS:
        if doc['id'] == doc_id:
            return doc
    return None
